redmine_mass_editor/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from mass_editor.views import step_one, step_two, step_three, download_data, upload_data, step_four, step_five, progress, stop_process
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy



urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('step_one')), name='home'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
    path('step-one/', step_one, name='step_one'),
    path('step-two/', step_two, name='step_two'),
    path('step-three/', step_three, name='step_three'),
    path('download-data/', download_data, name='download_data'),
    path('upload-data/', upload_data, name='upload_data'),
    path('step-four/', step_four, name='step_four'),
    path('step-five/', step_five, name='step_five'),
    path('progress/', progress, name='progress'),
    path('stop-process/', stop_process, name='stop_process'),
]

mass_editor/models.py
from django.db import models

mass_editor/forms.py
from django import forms
from .service.fields import getAllFields

class CustomFieldForm(forms.Form):
    options = forms.MultipleChoiceField(
        choices=getAllFields,
        widget=forms.SelectMultiple,
        required=True,
        label="Custom Fields"
    )

mass_editor/views.py
from django.shortcuts import render, redirect
from .forms import CustomFieldForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from .service.updateThread import update
from .service.fields import getAllFields, getFieldNameById
from threading import Thread
import csv
import time

@login_required
def step_one(request):
    getAllFields()
    if request.method == 'POST':
        form = CustomFieldForm(request.POST)
        if form.is_valid():
            # Hier können Sie die Logik implementieren, um die Auswahl zu speichern
            # Zum Beispiel könnten Sie die ausgewählten Felder in der Session speichern
            request.session['selected_options_identifier'] = form.cleaned_data['options']
            return redirect('step_two')  # Leiten Sie zum nächsten Schritt weiter
    else:
        form = CustomFieldForm()

    return render(request, 'step_one.html', {'form': form})


@login_required
def step_two(request):

    if request.method == 'POST':
        form = CustomFieldForm(request.POST)
        if form.is_valid():
            request.session['selected_options_columns'] = form.cleaned_data['options']
            print(form.cleaned_data['options'])
            return redirect('step_three')  # Leiten Sie zum nächsten Schritt weiter
    else:
        form = CustomFieldForm()

    return render(request, 'step_two.html', {'form': form})


@login_required
def step_three(request):
    return render(request, 'step_three.html')

@login_required
def download_data(request):
    # Implementieren Sie hier die Logik für den Download der Daten
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="template.csv"'
    # Schreiben Sie Daten in die Response
    header_arrays = request.session.get('selected_options_identifier', '') + request.session['selected_options_columns']

    header_names = []
    for header in header_arrays:
        header_names.append(getFieldNameById(header))
        
    header_string = ";".join(header_names)
    response.write(header_string+"\n")
    return response

@login_required
def upload_data(request):
    if request.method == 'POST' and request.FILES['file_upload']:
        uploaded_file = request.FILES['file_upload']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        file_url = fs.url(name)
        request.session['uploaded_csv_file_path'] = fs.path(name)  # Speichern des Pfads in der Session
        return redirect('step_four')
    return redirect('step_three')

@login_required
def step_four(request):
    csv_file_path = request.session.get('uploaded_csv_file_path', '')
    csv_headers = []
    csv_rows = []

    if csv_file_path:
        try:
            with open(csv_file_path, newline='', encoding='utf-8') as csvfile:
                reader = csv.reader(csvfile, delimiter=';')
                csv_headers = next(reader)  # Erste Zeile als Header
                csv_rows = list(reader)
        except Exception as e:
            print(f"Fehler beim Lesen der CSV-Datei: {e}")
    else:
        print("Kein Dateipfad in der Session gefunden.")

    return render(request, 'step_four.html', {
        'csv_headers': csv_headers,
        'csv_rows': csv_rows,
    })


@login_required
def step_five(request):
    thread = Thread(target = update, args = (request, ))
    thread.start()

    return render(request, 'step_five.html')

@login_required
def progress(request):
    # Beispiel: Abrufen des Fortschritts aus der Session
    progress = request.session.get('progress', 0)
    print(progress)
    return JsonResponse({'progress': progress})

@login_required
def stop_process(request):
    request.session['stop_requested'] = True
    request.session.save()
    return JsonResponse({'status': 'stop_requested'})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Redmine Mass Editor{% endblock %}</title>
    <!-- Optional: Einbinden von CSS-Dateien -->
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
</head>
<body style="display: flex; flex-direction: column;align-items: center;margin: 0;min-height: 100vh;">
    <header>
        <nav>
            <a href="#" class="brand">
                <img class="logo" src="{% static 'images/logo.png' %}" alt="Redmine Mass Editor Logo">
                <span>Redmine Mass Editor</span>
            </a>

            <div class="menu">
                <a href="../admin" class="pseudo button icon-picture">Admin</a>
                <form action="{% url 'logout' %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class='error'>Logout</button>
                </form>
              </div>
        </nav>
    </header>
    <br>
    <br>
    <br>
    <main style="width: 70%;display: flex;flex-direction: column;align-items: center;">

        {% block content %}
        <!-- Der Inhalt der abgeleiteten Templates wird hier platziert -->
        {% endblock %}

    </main>

    <footer>
        <!-- Fußzeile der Seite -->
        <p>&copy; 2024 CeeFeS: Redmine Mass Editor</p>
    </footer>

</body>
</html>

templates/login.html
<!-- templates/login.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  <div class="third">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
</div>
{% endblock %}

templates/step_five.html
{% extends 'base.html' %}

{% block content %}
  <h3>Step Five: Processing</h3>

  <!-- Ladebalken -->
  <div id="progress-container" style="width: 100%; background-color: #ddd;">
    <div id="progress-bar" style="width: 0%; height: 30px; background-color: #4CAF50;"></div>
  </div>
  
  <!-- Nicht editierbare Textarea für Fehler -->
  <textarea id="error-log" rows="10" style="width: 100%;" readonly></textarea>
  <button id="stop-button" onclick="stopProcess()">Stop Process</button>
  
  <script>
    function stopProcess() {
    fetch('/stop-process/')
      .then(response => response.json())
      .then(data => {
      if(data.status === 'stop_requested') {
        console.log('Stopp wurde erfolgreich angefordert.');
        // Optional: UI-Feedback geben, dass der Prozess gestoppt wird
      }
    })
    .catch(error => console.error('Fehler beim Anfordern des Stopps:', error));
    }

    function updateProgressBar() {
      fetch('/progress/')  // Pfad zur 'progress'-View
        .then(response => response.json())
        .then(data => {
          const progressBar = document.getElementById('progress-bar');
          const progress = data.progress;  // Fortschritt vom Server
          progressBar.style.width = progress + '%';
          
          // Wenn der Fortschritt weniger als 100% ist, weiterhin aktualisieren
          if(progress < 100) {
            setTimeout(updateProgressBar, 1000);  // Warte 1 Sekunde, dann frage erneut ab
          } else {
            // Optional: Fertigstellungshandlung, z.B. Anzeigen von Nachrichten
            document.getElementById('error-log').innerText = 'Prozess abgeschlossen. Hier sind Ihre Ergebnisse...';
          }
        })
        .catch(error => console.error('Fehler beim Abrufen des Fortschritts:', error));
    }
  
    // Starte die Fortschrittsaktualisierung, wenn die Seite geladen wird
    document.addEventListener('DOMContentLoaded', updateProgressBar);
  </script>
  
{% endblock %}

templates/step_four.html
{% extends 'base.html' %}

{% block content %}
  <h3>Step Four: Review Data</h3>
  
  <!-- Anzeigen der CSV-Daten als Tabelle -->
  <table>
    <thead>
      <tr>
        {% for header in csv_headers %}
          <th>{{ header }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
      {% for row in csv_rows %}
        <tr>
          {% for cell in row %}
            <td>{{ cell }}</td>
          {% endfor %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
  
  <!-- "Start process"-Button -->
  <form method="post" action="{% url 'step_five' %}">
    {% csrf_token %}
    <button type="submit">Start process</button>
  </form>
{% endblock %}

templates/step_one.html
{% extends 'base.html' %}

{% block content %}
<h3>Step One: Please select the identifiers (one or more)</h3>
  <form method="post">
    {% csrf_token %}
    <label for="id_options">{{ form.options.label }}</label>
    {{ form.options }}
    <button class="button" for="tabC-2" type="submit">Continue</button>
  </form>
{% endblock %}

templates/step_three.html
{% extends 'base.html' %}

{% block content %}
<article class="card">
    <header>
        <h3>Step Three</h3>
    </header>
  
  <!-- Download-Button -->
  <form method="get" action="{% url 'download_data' %}">
    <button type="submit">Download Data</button>
  </form>
  
  <!-- Hilfetext -->
  <p>Bitte laden Sie die bearbeitete Datei hier hoch, nachdem Sie die Daten heruntergeladen und bearbeitet haben.</p>
  
  <!-- Upload-Formular -->
  <form method="post" action="{% url 'upload_data' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file_upload">
    <button type="submit">Upload Data</button>
  </form>
</article>
{% endblock %}

templates/step_two.html
{% extends 'base.html' %}

{% block content %}
<h3>Step Two: Please select the columns you want to change.</h3>
  <form method="post">
    {% csrf_token %}
    <label for="id_options">{{ form.options.label }}</label>
    {{ form.options }}
    <button class="button" for="tabC-2" type="submit">Continue</button>
  </form>
{% endblock %}